version = 1
SPDX-PackageName = "slang-format"
SPDX-PackageSupplier = "Hudson River Trading <opensource@hudson-trading.com>"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "Hudson River Trading"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "external/BS_thread_pool.hpp"
precedence = "aggregate"
SPDX-FileCopyrightText = "Barak Shoshany"
SPDX-License-Identifier = "MIT"
