#!/usr/bin/env python3
"""Regenerate the formatter JSON schema and configuration reference."""

from __future__ import annotations

import argparse
import json
import subprocess
import tempfile
from pathlib import Path


def run(command: list[str], cwd: Path) -> str:
    return subprocess.run(
        command, cwd=cwd, check=True, text=True, capture_output=True
    ).stdout


def schema_type(value: dict) -> str:
    if "$ref" in value:
        return value["$ref"].split("/")[-1].split("__")[-1]
    if "oneOf" in value:
        return "string"
    if "anyOf" in value:
        return " | ".join(schema_type(item) for item in value["anyOf"])
    if value.get("type") == "array":
        return f"list[{schema_type(value.get('items', {}))}]"
    return value.get("type", "unknown")


def markdown_default(value: object) -> str:
    return f"`{json.dumps(value, separators=(',', ':'))}`"


def generate_markdown(schema: dict, defaults: dict) -> str:
    definitions = schema.get("$defs") or schema.get("definitions") or {}
    root_name = schema["$ref"].split("/")[-1]
    lines = [
        "<!-- This file is @generated by scripts/genconfig.py. Do not edit by hand. -->",
        "",
        "# Configuration",
        "",
        "`slang-format` reads JSON configuration from `.slang/format.json`. It searches",
        "upward from each file independently, then from the current working directory.",
        "An explicit `--config <path>` or `--config-json '<json>'` takes precedence.",
        "These options cannot be combined; omitted settings use built-in defaults.",
        "",
        "To configure formatting without a file:",
        "",
        "```sh",
        'slang-format --config-json \'{"columnLimit":80,"indentWidth":2}\' file.sv',
        "```",
        "",
        "All options are optional. Run `slang-format --dump-config` to print the",
        "resolved configuration for the first target (or stdin's assumed filename).",
        "Unknown keys are errors, including keys inside nested objects.",
        "Nested configs replace parent configs; omitted options use built-in defaults.",
        "Directory selection (`projectPaths` and `excludeDirectoryNames`) uses each",
        "directory argument's config; each file then resolves its own formatting settings.",
        "",
        "`projectPaths` entries resolve from the project root containing `.slang/`.",
        "For example, `src` in `project/.slang/format.json`",
        "selects `project/src` when `project` is targeted.",
        "",
        "## Config Options",
        "",
    ]

    def emit(properties: dict, values: dict, prefix: str = "") -> None:
        nested: list[tuple[str, dict, dict]] = []
        for name, prop in properties.items():
            full_name = f"{prefix}{name}"
            lines.extend(
                [f"### `{full_name}`", "", f"**Type:** `{schema_type(prop)}`", ""]
            )
            if name in values and "$ref" not in prop:
                lines.extend([f"**Default:** {markdown_default(values[name])}", ""])
            description = prop.get("description", "")
            if description:
                lines.extend([description, ""])
            if "oneOf" in prop:
                lines.extend(["**Values:**", ""])
                for item in prop["oneOf"]:
                    lines.append(
                        f"- `{json.dumps(item.get('const'))}` — {item.get('description', '')}"
                    )
                lines.append("")
            if "$ref" in prop:
                ref_name = prop["$ref"].split("/")[-1]
                nested.append(
                    (
                        f"{full_name}.",
                        definitions.get(ref_name, {}).get("properties", {}),
                        values.get(name, {})
                        if isinstance(values.get(name), dict)
                        else {},
                    )
                )
        for nested_prefix, nested_properties, nested_values in nested:
            emit(nested_properties, nested_values, nested_prefix)

    emit(definitions[root_name].get("properties", {}), defaults)
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    repo = Path(__file__).resolve().parent.parent
    parser = argparse.ArgumentParser()
    parser.add_argument("--build-dir", type=Path, default=repo / "build")
    args = parser.parse_args()
    build_dir = args.build_dir.resolve()

    subprocess.run(["cmake", "-B", str(build_dir)], cwd=repo, check=True)
    subprocess.run(
        [
            "cmake",
            "--build",
            str(build_dir),
            "-j8",
            "--target",
            "gen_format_config_schema",
            "slang_format",
        ],
        cwd=repo,
        check=True,
    )

    schema_text = run([str(build_dir / "bin" / "gen_format_config_schema")], repo)
    schema = json.loads(schema_text)
    schema_path = repo / "schemas" / "format.schema.json"
    schema_path.parent.mkdir(parents=True, exist_ok=True)
    schema_path.write_text(json.dumps(schema, indent=2) + "\n")

    with tempfile.TemporaryDirectory() as temp_dir:
        defaults = json.loads(
            run(
                [str(build_dir / "bin" / "slang-format"), "--dump-config"],
                Path(temp_dir),
            )
        )
    (repo / "docs" / "features" / "configuration.md").write_text(
        generate_markdown(schema, defaults)
    )


if __name__ == "__main__":
    main()
