//------------------------------------------------------------------------------
// FormatStyle.cpp
// Style decision functions for the SystemVerilog formatter
//
// SPDX-FileCopyrightText: Hudson River Trading
// SPDX-License-Identifier: MIT
//------------------------------------------------------------------------------

#include "format/FormatStyle.h"

#include "slang/parsing/TokenKind.h"
#include "slang/syntax/AllSyntax.h"
#include "slang/syntax/SyntaxFacts.h"

using namespace slang::parsing;
using namespace slang::syntax;

namespace format {

// Generated by scripts/gen_format_style.py -- do not edit these functions.
#include "FormatStyleGen.inc"

bool nodeNeedsOwnLine(SyntaxKind parentKind, size_t listIndex) {
    // MemberSyntax always has attributes in list slot 0.
    if (MemberSyntax::isKind(parentKind) && listIndex == 0)
        return true;
    // StatementSyntax has label first, then attributes in list slot 0.
    if (StatementSyntax::isKind(parentKind) && listIndex == 0)
        return true;
    // Remaining types detected by generated function.
    if (listIndex == 0 && isNonstandardAttributeListSyntax(parentKind))
        return true;
    return false;
}

bool isCloseDelim(TokenKind kind) {
    switch (kind) {
        case TokenKind::CloseBrace:
        case TokenKind::CloseBracket:
        case TokenKind::CloseParenthesis:
            return true;
        default:
            return false;
    }
}

bool isOpenDelim(TokenKind kind) {
    switch (kind) {
        case TokenKind::OpenParenthesis:
        case TokenKind::OpenBrace:
        case TokenKind::OpenBracket:
            return true;
        default:
            return false;
    }
}

bool shouldInsertWhitespace(TokenKind left, TokenKind right, SyntaxKind leftParent,
                            SyntaxKind rightParent, bool rightInDataType) {
    // No previous token yet -- doesn't matter, caller handles line start.
    if (left == TokenKind::Unknown)
        return false;

    // No space before closing punctuation delimiters.
    if (isCloseDelim(right))
        return false;

    // No space after opening keywords.
    if (isOpenDelim(left))
        return false;

    // No space after opening punctuation delimiters.
    if (left == TokenKind::OpenParenthesis || left == TokenKind::OpenBracket ||
        left == TokenKind::OpenBrace || left == TokenKind::ApostropheOpenBrace) {
        return false;
    }

    if (right == TokenKind::ApostropheOpenBrace && left == TokenKind::Identifier) {
        return false;
    }

    // An empty case-item clause renders as `LABEL: ;` / `default: ;` — keep a
    // space between the case-item colon and the empty statement's semicolon.
    // (General rule below is no space before `;`.)
    if (SyntaxFacts::isSemicolon(right) && left == TokenKind::Colon &&
        (leftParent == SyntaxKind::StandardCaseItem || leftParent == SyntaxKind::DefaultCaseItem))
        return true;

    // No space before comma or semicolon.
    if (SyntaxFacts::isComma(right) || SyntaxFacts::isSemicolon(right))
        return false;

    // Always space after comma.
    if (SyntaxFacts::isComma(left))
        return true;

    // No space around member access dot.
    if (left == TokenKind::Dot || right == TokenKind::Dot)
        return false;

    // No space around scope resolution.
    if (left == TokenKind::DoubleColon || right == TokenKind::DoubleColon)
        return false;

    // No space after # (parameter override / delay).
    if (left == TokenKind::Hash)
        return false;

    // No space after @ (event control).
    if (left == TokenKind::At)
        return false;

    // No space around apostrophe in cast expressions: int'(x), unsigned'(y), void'(f()).
    if (right == TokenKind::Apostrophe && (rightParent == SyntaxKind::CastExpression ||
                                           rightParent == SyntaxKind::SignedCastExpression ||
                                           rightParent == SyntaxKind::VoidCastedCallStatement)) {
        return false;
    }
    if (left == TokenKind::Apostrophe && (leftParent == SyntaxKind::CastExpression ||
                                          leftParent == SyntaxKind::SignedCastExpression ||
                                          leftParent == SyntaxKind::VoidCastedCallStatement)) {
        return false;
    }

    // No space before [ when it follows an identifier-like token (bit select /
    // array indexing / declarator dimensions).  In data type contexts
    // (type dimensions like `some_t [7:0]`), insert a space -- but consecutive
    // packed dimensions like `[7:0][3:0]` never get a space between them.
    if (right == TokenKind::OpenBracket) {
        if (left == TokenKind::CloseBracket)
            return false;
        if (!rightInDataType &&
            (left == TokenKind::Identifier || left == TokenKind::CloseParenthesis ||
             left == TokenKind::MacroUsage)) {
            return false;
        }
    }

    if (right == TokenKind::Colon) {
        if (left == TokenKind::BeginKeyword)
            return true;
        // Ternary conditional: a ? b : c
        if (rightParent == SyntaxKind::ConditionalExpression)
            return true;
        return false;
    }

    // No space around integer base and its adjacent parts: 32'h, 'hFF.
    // But allow space before unsized base after operators: + 'd1.
    if (left == TokenKind::IntegerBase)
        return false;
    if (right == TokenKind::IntegerBase && left == TokenKind::IntegerLiteral)
        return false;

    // Space before ( in module/interface port lists and instance connections:
    // `module foo (`, `child u_byte (`, `) (`.
    if (right == TokenKind::OpenParenthesis) {
        if (rightParent == SyntaxKind::AnsiPortList || rightParent == SyntaxKind::NonAnsiPortList ||
            rightParent == SyntaxKind::WildcardPortList ||
            rightParent == SyntaxKind::HierarchicalInstance ||
            leftParent == SyntaxKind::HierarchyInstantiation) {
            return true;
        }
        // No space after identifiers in all other contexts (function calls,
        // named port connections, task/function declarations).
        // Also no space after `iff` keyword: `disable iff(expr)`.
        if (left == TokenKind::Identifier || left == TokenKind::SystemIdentifier ||
            left == TokenKind::CloseParenthesis || left == TokenKind::CloseBracket ||
            left == TokenKind::MacroUsage || left == TokenKind::IffKeyword ||
            left == TokenKind::NewKeyword) {
            return false;
        }
    }

    // No space around the power operator: a**b, not a ** b.
    if (left == TokenKind::DoubleStar || right == TokenKind::DoubleStar)
        return false;

    // No space after prefix unary operator (e.g., !a, ~b, &c).
    if (PrefixUnaryExpressionSyntax::isKind(leftParent))
        return false;

    // No space before postfix unary operator (e.g., a++, b--).
    if (PostfixUnaryExpressionSyntax::isKind(rightParent))
        return false;

    // Default: insert whitespace.
    return true;
}

} // namespace format
